# Generated by Django 4.0 on 2021-12-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
