# Generated by Django 4.0 on 2021-12-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
