# Generated by Django 4.0 on 2021-12-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_no_of_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
