# Generated by Django 4.0 on 2021-12-18 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_customuser_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 18, 13, 29, 16, 941284))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 12, 18, 13, 29, 16, 941284))),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
